#!/bin/bash
# mdz is the front end, which in turns call other files

set -e -o pipefail
shopt -s failglob 

error(){
	echo Error: $*
	exit -1
}

read_config(){
  ENV=$(env | grep '^MDZ') || true
  if [ -f "$MDZ_CONFIG" ]; then
	source "$MDZ_CONFIG"
  elif [ -f ~/.medusa.conf ]; then
	source ~/.medusa.conf
  elif [ -f /etc/medusa.conf ]; then
	source /etc/medusa.conf
  else
	error "no config file found! Set \$MDZ_CONFIG or add ~/.medusa.conf"
  fi
  eval "$ENV"
}

usage(){
  echo "Usage: mdz [command] [options]"
  echo "       mdz --help"
}

serve(){
    [ -x "$MDZ_DIR/services/$1/$1.sh" ] || error "No such service: $1"
    "$MDZ_DIR/services/$1/$1.sh" "${@:2}"
}

run(){
    [ -x "$MDZ_DIR/run/$1.sh" ] || error "No such command: $1"
    "$MDZ_DIR/run/$1.sh" "${@:2}"
}

read_config

# Set up defaults:
[ -z "$MDZ_QUICK_MODE" ] && MDZ_QUICK_MODE=0
export MDZ_QUICK_MODE MDZ_DIR MDZ_DATADIR MDZ_REPOSITORY MDZ_REPO_METHOD

[ -z "$MDZ_WEBSITE_DATA_PREFIX" ] && MDZ_WEBSITE_DATA_PREFIX=data
export MDZ_WEBSITE_DIR MDZ_WEBSITE_DATA_PREFIX

[ -z "$MDZ_XAPIAN_DB" ] && MDZ_XAPIAN_DB=medusa
export MDZ_XAPIAN_DIR MDZ_XAPIAN_DB

export MDZ_VIROBLAST_DIR

. "$MDZ_DIR/functions.sh"

CMD=$1
PARAMS="${@:2}"

case $CMD in
  check)
	$MDZ_DIR/xmlcheck.sh $PARAMS
  ;;
  checkall)
	$MDZ_DIR/checkall.sh $PARAMS
  ;;
  get)
	$MDZ_DIR/get.sh $PARAMS
  ;;
  put)
	$MDZ_DIR/put.sh $PARAMS
  ;;
  list)
	$MDZ_DIR/list.sh $PARAMS
  ;;
  genmeta)
	$MDZ_DIR/gen_meta.sh $PARAMS
  ;;
  service)
	serve $PARAMS
  ;;
  run)
	run $PARAMS
  ;;
  --help)
	usage
        echo
	cat <<EOF
Available commands:

  check    - check a dataset for correctness
  checkall - check all datasets
  get      - get a dataset from remote repository
  put      - put a dataset in remote repository
  list     - list contenst of remote repository
  genmeta  - generate metadata for a dataset

  service <serv> - service specific commmands
  run <cmd>      - run pipeline to generate new datasets
EOF
  echo "Available services: " $(ls $MDZ_DIR/services)
  echo "Available commands: " $(ls $MDZ_DIR/run/ | grep '\.sh$' | sed -e 's/\.sh$//g')
  ;;
  *)
 	usage
  ;;
esac
